name: CI/CD
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Run every day at utc midnight
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BOT_NAME: github-actions[bot]
    steps:
      - name: Pull Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install playwrights
        run: |
          npx -y playwright install

      - name: Test
        id: test
        run: npm run test

      - name: Upload test result
        if: always()
        run: echo "Uploading test result..."

      - name: Deploy
        run: |
          # Deploy the app to a staging environment
          echo "Deploying to staging..."
